CREATE TABLE `audit_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`company_id` int,
	`user_id` int,
	`user_name` varchar(150),
	`acao` varchar(100) NOT NULL,
	`entidade` varchar(50),
	`entidade_id` int,
	`dados_antes` json,
	`dados_depois` json,
	`ip` varchar(45),
	`user_agent` varchar(300),
	`created_at` timestamp DEFAULT (now()),
	CONSTRAINT `audit_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `centros_custo` (
	`id` int AUTO_INCREMENT NOT NULL,
	`obra_id` int NOT NULL,
	`company_id` int NOT NULL,
	`codigo` varchar(20) NOT NULL,
	`nome` varchar(150) NOT NULL,
	`categoria_cc` enum('material','mao_obra','equipamento','subempreiteiro','indireto','servico') NOT NULL,
	`orcado` decimal(15,2) DEFAULT '0',
	`realizado` decimal(15,2) DEFAULT '0',
	`created_at` timestamp DEFAULT (now()),
	CONSTRAINT `centros_custo_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contas_pagar` (
	`id` int AUTO_INCREMENT NOT NULL,
	`company_id` int NOT NULL,
	`obra_id` int,
	`centro_custo_id` int,
	`descricao` varchar(300) NOT NULL,
	`fornecedor` varchar(200),
	`categoria_cp` enum('material','servico','equipamento','subempreiteiro','imposto','outro') DEFAULT 'servico',
	`valor` decimal(15,2) NOT NULL,
	`vencimento` date NOT NULL,
	`data_pagamento` date,
	`status_cp` enum('pendente','pago','vencido','cancelado') DEFAULT 'pendente',
	`nfe_id` int,
	`comprovante` varchar(500),
	`observacoes` text,
	`lancado_por_id` int,
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `contas_pagar_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contas_receber` (
	`id` int AUTO_INCREMENT NOT NULL,
	`company_id` int NOT NULL,
	`obra_id` int,
	`cliente_id` int,
	`descricao` varchar(300) NOT NULL,
	`numero_medicao` varchar(50),
	`valor` decimal(15,2) NOT NULL,
	`vencimento` date NOT NULL,
	`data_recebimento` date,
	`status_cr` enum('pendente','recebido','vencido','cancelado') DEFAULT 'pendente',
	`comprovante` varchar(500),
	`observacoes` text,
	`lancado_por_id` int,
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `contas_receber_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `dre_obra` (
	`id` int AUTO_INCREMENT NOT NULL,
	`obra_id` int NOT NULL,
	`company_id` int NOT NULL,
	`periodo` varchar(7) NOT NULL,
	`receita_bruta` decimal(15,2) DEFAULT '0',
	`deducoes` decimal(15,2) DEFAULT '0',
	`receita_liquida` decimal(15,2) DEFAULT '0',
	`custo_material` decimal(15,2) DEFAULT '0',
	`custo_mao_obra` decimal(15,2) DEFAULT '0',
	`custo_equipamento` decimal(15,2) DEFAULT '0',
	`custo_subempreiteiro` decimal(15,2) DEFAULT '0',
	`custo_indireto` decimal(15,2) DEFAULT '0',
	`custo_total` decimal(15,2) DEFAULT '0',
	`lucro_bruto` decimal(15,2) DEFAULT '0',
	`margem_bruta` decimal(5,2) DEFAULT '0',
	`gerado_em` timestamp DEFAULT (now()),
	`gerado_por_id` int,
	CONSTRAINT `dre_obra_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lancamentos_custo` (
	`id` int AUTO_INCREMENT NOT NULL,
	`obra_id` int NOT NULL,
	`centro_custo_id` int,
	`company_id` int NOT NULL,
	`tipo_lancamento` enum('material','mao_obra','equipamento','subempreiteiro','indireto','servico') NOT NULL,
	`descricao` varchar(300) NOT NULL,
	`fornecedor` varchar(200),
	`quantidade` decimal(10,3) DEFAULT '1',
	`unidade` varchar(20) DEFAULT 'un',
	`valor_unitario` decimal(15,2) NOT NULL,
	`valor_total` decimal(15,2) NOT NULL,
	`status_lancamento` enum('pendente','aprovado','pago','cancelado') DEFAULT 'pendente',
	`data_competencia` date,
	`data_pagamento` date,
	`nfe_id` int,
	`nfe_numero` varchar(50),
	`classificado_por_ia` boolean DEFAULT false,
	`confianca_ia` decimal(5,2),
	`lancado_por_id` int,
	`observacoes` text,
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lancamentos_custo_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `mao_de_obra` (
	`id` int AUTO_INCREMENT NOT NULL,
	`company_id` int NOT NULL,
	`obra_id` int,
	`nome` varchar(150) NOT NULL,
	`cpf` varchar(14),
	`tipo_mdo` enum('funcionario','terceiro','empreiteiro') DEFAULT 'funcionario',
	`funcao` varchar(100),
	`custo_diario` decimal(10,2),
	`custo_hora` decimal(10,2),
	`ativo` boolean DEFAULT true,
	`data_admissao` date,
	`data_demissao` date,
	`created_at` timestamp DEFAULT (now()),
	CONSTRAINT `mao_de_obra_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `notas_fiscais` (
	`id` int AUTO_INCREMENT NOT NULL,
	`company_id` int NOT NULL,
	`obra_id` int,
	`tipo_nf` enum('nfe','nfse','nfce') DEFAULT 'nfe',
	`numero` varchar(20),
	`serie` varchar(5),
	`chave_acesso` varchar(44),
	`data_emissao` date,
	`emitente_cnpj` varchar(18),
	`emitente_nome` varchar(200),
	`destinatario_cnpj` varchar(18),
	`destinatario_nome` varchar(200),
	`valor_total` decimal(15,2),
	`valor_produtos` decimal(15,2),
	`valor_servicos` decimal(15,2),
	`valor_impostos` decimal(15,2),
	`xml_url` varchar(500),
	`pdf_url` varchar(500),
	`itens_classificados` json,
	`classificado_por_ia` boolean DEFAULT false,
	`obra_vinculada_por_ia` boolean DEFAULT false,
	`status_nf` enum('importada','processando','classificada','vinculada','erro') DEFAULT 'importada',
	`erro_processamento` text,
	`importada_por_id` int,
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `notas_fiscais_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `obras` (
	`id` int AUTO_INCREMENT NOT NULL,
	`company_id` int NOT NULL,
	`codigo` varchar(30) NOT NULL,
	`nome` varchar(200) NOT NULL,
	`descricao` text,
	`tipo_obra` enum('instalacao','manutencao','reforma','inspecao','projeto','outro') DEFAULT 'instalacao',
	`status_obra` enum('planejamento','em_andamento','pausada','concluida','cancelada') DEFAULT 'planejamento',
	`endereco` varchar(300),
	`cidade` varchar(100),
	`estado` varchar(2),
	`cep` varchar(9),
	`responsavel_id` int,
	`cliente_id` int,
	`data_inicio_prevista` date,
	`data_fim_prevista` date,
	`data_inicio_real` date,
	`data_fim_real` date,
	`orcamento_total` decimal(15,2) DEFAULT '0',
	`custo_real_total` decimal(15,2) DEFAULT '0',
	`receita_contratada` decimal(15,2) DEFAULT '0',
	`margem_prevista` decimal(5,2),
	`observacoes` text,
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `obras_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `registros_ponto` (
	`id` int AUTO_INCREMENT NOT NULL,
	`mao_de_obra_id` int NOT NULL,
	`obra_id` int NOT NULL,
	`company_id` int NOT NULL,
	`data` date NOT NULL,
	`entrada` varchar(5),
	`saida` varchar(5),
	`horas_trabalhadas` decimal(5,2),
	`custo_calculado` decimal(10,2),
	`observacao` varchar(300),
	`registrado_por_id` int,
	`created_at` timestamp DEFAULT (now()),
	CONSTRAINT `registros_ponto_id` PRIMARY KEY(`id`)
);
