CREATE TABLE `fire_system_audit_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`inspection_id` int NOT NULL,
	`user_id` int NOT NULL,
	`user_name` varchar(255) NOT NULL,
	`action` varchar(100) NOT NULL,
	`entity_type` varchar(50) DEFAULT 'inspection',
	`entity_id` varchar(50),
	`previous_value` text,
	`new_value` text,
	`ip_address` varchar(45),
	`user_agent` varchar(500),
	`notes` text,
	`created_at` timestamp DEFAULT (now()),
	CONSTRAINT `fire_system_audit_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fire_system_inspections` (
	`id` int AUTO_INCREMENT NOT NULL,
	`company_id` int NOT NULL,
	`inspection_number` varchar(50) NOT NULL,
	`status` enum('draft','in_progress','completed','approved','rejected') NOT NULL DEFAULT 'draft',
	`approval_status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`enterprise_name` varchar(255) NOT NULL,
	`shopping_name` varchar(255),
	`store_name` varchar(255),
	`address` text,
	`city` varchar(100),
	`state` varchar(2),
	`responsible_local` varchar(255),
	`inspector_name` varchar(255) NOT NULL,
	`engineer_name` varchar(255),
	`engineer_crea` varchar(50),
	`art_number` varchar(50),
	`inspection_date` timestamp DEFAULT (now()),
	`operation_type` varchar(100),
	`fuel_type` varchar(100),
	`cooking_classification` varchar(100),
	`system_classification` varchar(100),
	`general_notes` text,
	`score_total` decimal(5,2) DEFAULT '0.00',
	`risk_classification` enum('R1','R2','R3','R4','R5') NOT NULL DEFAULT 'R1',
	`audit_hash` varchar(64),
	`report_slug` varchar(100),
	`report_url` text,
	`last_maintenance_provider` varchar(255),
	`created_by_user_id` int NOT NULL,
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fire_system_inspections_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fire_system_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`inspection_id` int NOT NULL,
	`section_code` varchar(10) NOT NULL,
	`section_name` varchar(255) NOT NULL,
	`item_code` varchar(10) NOT NULL,
	`title` varchar(500) NOT NULL,
	`norm_ref` varchar(50),
	`status` enum('pending','conforming','non_conforming','not_applicable','critical') NOT NULL DEFAULT 'pending',
	`risk_level` int DEFAULT 1,
	`risk_code` varchar(5) DEFAULT 'R1',
	`weight` decimal(4,1) DEFAULT '1.0',
	`score` decimal(4,2) DEFAULT '0.00',
	`measurement_type` varchar(50),
	`measurement_value_text` text,
	`measurement_value_numeric` decimal(10,3),
	`measurement_unit` varchar(30),
	`expected_min` decimal(10,3),
	`expected_max` decimal(10,3),
	`manual_comment` text,
	`short_comment` text,
	`ai_comment` text,
	`recommended_action` text,
	`photo_urls` text,
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fire_system_items_id` PRIMARY KEY(`id`)
);
